5-团队作业/mytry/learn/urls.py
# learn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # 空路径（即/learn/）将会调用learn应用的index视图
]

5-团队作业/mytry/mytry/urls.py
from django.contrib import admin
from django.urls import path
from learn.views import index
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('captcha/', include('captcha.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # path('', include('userprofile.urls')),
    path('password_reset/', PasswordResetView.as_view(template_name='userprofile/password_reset_form.html',
                                                      email_template_name='userprofile/password_reset_email.html',),
         name='password_reset'),
    path('learn/', include('learn.urls')),  # 这里包含learn应用的URL配置
    path('SmartCenter/', include('SmartCenter.urls')),  
    path('DataCenter/', include('DataCenter.urls')),  
    path('BackManage/', include('BackManage.urls')),  
    path('MainInformation/', include('MainInformation.urls')),  
    path('UnderWater/', include('UnderWater.urls')),  

]
#设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

5-团队作业/mytry/userprofile/urls.py
from django.urls import path
from .views import *

app_name = 'userprofile'

urlpatterns = [
    path('login/', user_login, name='login'),
    # path('', user_login),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('profile/', user_profile, name='profile'),
]

5-团队作业/mytry/userprofile/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models


class UserProfile(AbstractUser):
    avatar = models.ImageField(upload_to="avatar/%Y%m%d/", default="avatar/20210705/default.png", blank=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.username

5-团队作业/mytry/userprofile/forms.py
from django import forms

from userprofile.models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class RegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            return forms.ValidationError('两次输入的密码不一致，请重新输入！')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)

5-团队作业/mytry/userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect


from userprofile.forms import LoginForm, RegisterForm, ProfileForm
from userprofile.models import UserProfile as User
from django.contrib.auth import get_user_model

def user_login(request):
    if request.method == "GET":
        login_form = LoginForm()
        context = {"login_form": login_form}
        return render(request, "userprofile/login.html", context)
    else:
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            # data = login_form.cleaned_data
            # user = authenticate(username=data['username'], password=data['password'])
            data = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=data, password=password)
            
             # 如果使用用户名没有找到用户，尝试邮箱登录
            if user is None:
                try:
                    user_by_email = User.objects.get(email=data)
                    # 使用邮箱找到用户后，再次尝试认证
                    user = authenticate(request, username=user_by_email.username, password=password)
                    authority = (User.objects.get(email=data).is_superuser & User.objects.get(email=data).is_staff)
                except User.DoesNotExist:
                    user_by_email = None
            else:
                authority = (User.objects.get(username=data).is_superuser & User.objects.get(username=data).is_staff)
            if user:
                login(request, user)
                # return redirect("article:article-list")
                # return redirect("index") 
                # return render(request, 'SmartCenter/trend.html', context)
                # return render(request, 'SmartCenter/your_template.html', {'context_data': data})
                # 数据查询，根据用户名查询出用户的权限
                # authority = (User.objects.get(username=data['username']).is_superuser & User.objects.get(username=data['username']).is_staff)

                if authority:
                    # return redirect("BackManage") 
                    return redirect("MainInformation") 
                    
                else:
                    # return redirect("MainInformation")
                    return redirect("MainInformation_user") 

            else:
                context = {'obj': login_form, 'error': '账号或密码错误，请重新输入！'}
                return render(request, 'userprofile/login.html', context)
        else:
            context = {'obj': login_form, 'error': login_form.errors}
            return render(request, 'userprofile/login.html', context)


def user_logout(request):
    logout(request)
    return redirect("article:article-list")


def user_register(request):
    if request.method == 'GET':
        register_form = RegisterForm()
        context = {'register_form': register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        register_form = RegisterForm(data=request.POST)
        if register_form.is_valid():
            new_user = register_form.save(commit=False)
            new_user.set_password(register_form.cleaned_data['password'])
            new_user.save()
            return redirect("userprofile:login")
        else:
            context = {'obj': register_form, 'error': register_form.errors}
            return render(request, 'userprofile/register.html', context)


def user_profile(request):
    if request.method == "GET":
        articles = ArticlePost.objects.filter(author_id=request.user.id)
        context = {'articles': articles}
        return render(request, 'userprofile/profile.html', context)
    else:
        profile = UserProfile.objects.get(id=request.user.id)
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_form_data = profile_form.cleaned_data
            if 'avatar' in request.FILES:
                profile.avatar = profile_form_data['avatar']
            profile.save()
            return redirect('userprofile:profile')
        else:
            return HttpResponse('表单有误，请重新填写！')

5-团队作业/mytry/userprofile/templates/userprofile/login.html
<!--
 * @Author: HanJ
 * @Date: 2024-05-09 22:17:10
 * @LastEditors: Do not edit
 * @LastEditTime: 2024-05-10 11:58:23
 * @FilePath: \myTry\mytry\userprofile\templates\userprofile\login.html
-->
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- <link rel="icon" href="{% static 'img/logo.png' %}"> -->
</head>
<body>
<div class="container">
    <div class="col-4 shadow offset-4 bg-light" style="margin-top: 15%;">
        <form class='p-5' action="." method="post">
            {% csrf_token %}
            <span class="text-danger">{{ error }}</span>
            <div class="mb-3">
                <label for="username" class="form-label">账号</label>
                <!-- <input type="text" class="form-control" id="username" name="username" required> -->
                <input type="text" class="form-control" id="username" name="username" placeholder="输入用户名或邮箱" required>
            </div>
            <div class="mb-3">
                <label for="password" class="form-label">密码</label>
                <input type="password" class="form-control" id="password" name="password" required>
            </div>
            <div class="my-3 row">
                <div class="col-6 justify-content-start">
                    <a class="text-decoration-none float-start text-secondary py-2" href="{% url 'password_reset' %}">忘记密码？</a>
               </div>
                <div class="col-6 justify-content-end">
                    <a class="text-decoration-none float-end text-secondary py-2" href="{% url 'userprofile:register' %}">没有账号？</a>
                </div>
            </div>

            <div class="d-grid gap-3">
                <button type="submit" class="btn btn-primary">立即登录</button>
            </div>
        </form>
    </div>
</div>
</body>
</html>

5-团队作业/mytry/userprofile/templates/userprofile/password_reset_complete.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<div class="container m-5">
<p>你的密码己经重置完成，现在你可以继续进行登录。</p>

<p><a href="{% url 'userprofile:login' %}">登录</a></p>

</div>
</body>
</html>

5-团队作业/mytry/userprofile/templates/userprofile/password_reset_confirm.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<div class="container">
    <p class="text-center mt-5">请输入新密码两次，以便我们验证您键入的密码是否正确。</p>
    <div class="col-md-4 col-sm-6 border offset-md-4 offset-sm-6 p-5 mt-5 bg-light">
        {% if validlink %}
            <form method="post">{% csrf_token %}
                <fieldset>
                    <input class="visually-hidden" autocomplete="username" value="{{ form.user.get_username }}">
                    <div class="mb-3">
                        {{ form.new_password1.errors }}
                        <label class="form-label" for="id_new_password1">新密码：</label>
                        {{ form.new_password1 }}
                    </div>
                    <div class="mb-3">
                        {{ form.new_password2.errors }}
                        <label class="form-label" for="id_new_password2">确认密码：</label>
                        {{ form.new_password2 }}
                    </div>
                    <div class="d-grid">
                        <input class="btn btn-primary mt-3" type="submit" value="重置密码">
                    </div>
                </fieldset>
            </form>

        {% else %}

            <p>密码重置链接无效，可能是因为它已被使用。请重新设置密码。</p>

        {% endif %}
    </div>
</div>
<script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
<script>
    $('#id_new_password1').addClass('form-control');
    $('#id_new_password2').addClass('form-control');
</script>
</body>
</html>

5-团队作业/mytry/userprofile/templates/userprofile/password_reset_done.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<div class="container m-5 text-center">
<p>如果你所输入的电子邮箱存在对应的用户，我们将通过电子邮件向你发送设置密码的操作步骤说明。你应该很快就会收到。</p>

<p>如果你没有收到电子邮件，请检查输入的是你注册的电子邮箱地址。另外，也请检查你的垃圾邮件文件夹。</p>
</div>
</body>
</html>

5-团队作业/mytry/userprofile/templates/userprofile/password_reset_email.html
{% autoescape off %}
您收到这封邮件是因为您在请求重置您在网站{{ site_name }}上的用户帐户密码。

请访问该页面并设置一个新密码：
{% block reset_link %}
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}
{% endblock %}
提醒一下，您的用户名是：{{ user.get_username }}

感谢您使用我们的网站

{{ site_name }}团队

{% endautoescape %}

5-团队作业/mytry/userprofile/templates/userprofile/password_reset_form.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>找回密码</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="icon" href="{% static 'img/logo.png' %}">
</head>
<body>
    <div class="container m-5">
        <p>忘记密码？在下面输入你的电子邮箱地址，我们将会把设置新密码的操作步骤说明通过电子邮件发送给你。</p>
        <form method="post">
            {% csrf_token %}
            <fieldset>
                <div class="pb-3 mb-3 border-bottom">
                    {{ form.email.errors }}
                    <label for="id_email">电子邮件地址：</label>
                    {{ form.email }}
                </div>
                <input class="btn btn-primary" type="submit" value="重设我的密码">
            </fieldset>
        </form>
    </div>
</body>
</html>

5-团队作业/mytry/userprofile/templates/userprofile/profile.html
{% extends 'base.html' %}
{% block title %}个人中心{% endblock %}
{% block style %}
    .box{
        position: relative;
        overflow: hidden;
    }
    .box img{
        width: 100%;
        height: auto;
    }
    .box .box-content{
        width: 100%;
        height: 100%;
        position: absolute;
        top: 0;
        left: 0;
        color: #fff;
        text-align: center;
        padding: 40% 20px;
        background: rgba(0,0,0,0.6);
        transform: rotate(-90deg);
        transform-origin: left top 0;
        transition: all 0.50s ease 0s;
    }
    .box .read{
        font-size: 20px;
        font-weight: bold;
        color: #fff;
        display: block;
        letter-spacing:2px;
        transform: rotate(180deg);
        transform-origin: right top 0;
        transition: all 0.3s ease-in-out 0.2s;
    }
    .box .read:hover{
        color: #e8802e;
        text-decoration: none;
    }
    .box:hover .box-content,
    .box:hover .read {
        transform:rotate(0deg);
    }
    @media screen and (max-width: 990px){
        .box{ margin-bottom:20px; }
    }
    @media screen and (max-width: 359px){
        .box .box-content{ padding: 10% 20px; }
    }
{% endblock %}
{% block content %}
    <div class="container">
        <form action="." method="post" enctype="multipart/form-data" class="visually-hidden">
            {% csrf_token %}
            <input class="form-control" type="file" name="avatar" id="upload_avatar">
            <button type="submit" id="submit"></button>
        </form>
        <div class="row shadow mt-4 py-3">
            <div class="col-2">
                <div class="box">
                    <img src="{{ user.avatar.url }}" class="img-thumbnail mx-auto d-block" alt="头像">
                    <div class="box-content">
                        <span class="read" onclick="x()">更换头像</span>
                    </div>
                </div>
            </div>
            <div class="col-10">
                <h1>{{ user.username }}</h1>
                <p><i class="bi bi-calendar-check-fill"></i> 入园时间：{{ user.date_joined }}</p>
                <p><i class="bi bi-calendar-check"></i> 上次登录：{{ user.last_login }}</p>
                <p><i class="bi bi-envelope-fill"></i> 注册邮箱：{{ user.email }}</p>
            </div>
        </div>
        <div class="row mt-4">
            <div class="col-8 shadow">
                {% for article in articles %}
                    <div class="row">
                        <div class="card border-0 mt-3 h-250">
                            <div class="card-header">
                                <h5>{{ article.title }}</h5>
                                <small class="text-secondary"><i class="bi bi-clock"></i> 发表于 {{ article.created }}
                                </small>
                            </div>
                            <div class="card-body">
                                <p class="card-text">{{ article.body|slice:'100' }}</p>
                                <!-- slice:'100'是Django的过滤器语法，表示取出正文的前100个字符，避免摘要太长 -->
                                <a href="{% url 'article:article-detail' article.id %}" class="btn btn-primary">阅读本文</a>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
            <div class="col-3 offset-1 shadow">

            </div>
        </div>
    </div>
    <script>
        function x() {
            const $input = $('#upload_avatar');
            $input.click();
            $input.change(function () {
                //如果value不为空，调用文件加载方法
                if($(this).val() !== ""){
                    $("#submit").click();
                }
            })
        }
    </script>
{% endblock content %}

5-团队作业/mytry/userprofile/templates/userprofile/register.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <title>注册</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <link rel="icon" href="{% static 'img/logo.png' %}">
</head>
<body>
<div class="container">
    <div class="col-4 offset-4 bg-light shadow" style="margin-top: 15%;">
        <form class='p-5' action="." method="post">
            {% csrf_token %}
            <span class="text-danger">{{ error }}</span>
            <div class="input-group mb-4">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-person"></i></span>
                <input type="text" class="form-control" placeholder="用户名" name="username"
                       aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-4">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-envelope"></i></span>
                <input type="email" class="form-control" placeholder="邮箱" name="email"
                       aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-4">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-key"></i></span>
                <input type="password" class="form-control" placeholder="密码" name="password"
                       aria-describedby="basic-addon1" required>
            </div>
            <div class="input-group mb-4">
                <span class="input-group-text" id="basic-addon1"><i class="bi bi-key"></i></span>
                <input type="password" class="form-control" placeholder="确认密码" name="password2"
                       aria-describedby="basic-addon1" required>
            </div>
            <div class="d-grid gap-3">
                <button type="submit" class="btn btn-primary">立即注册</button>
            </div>
            <div class="mt-3 row">
                <div class="col-6 justify-content-start"></div>
                <div class="col-6 justify-content-end">
                    <a class="text-decoration-none float-end text-secondary" href="{% url 'userprofile:login' %}">已有账号？</a>
                </div>
            </div>
        </form>
    </div>
</div>
</body>
</html>