5-团队作业/mytry/learn/urls.py
# learn/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),  # 空路径（即/learn/）将会调用learn应用的index视图
]

5-团队作业/mytry/mytry/urls.py
from django.contrib import admin
from django.urls import path
from learn.views import index
from django.urls import path, include
from django.contrib.auth.views import PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, \
    PasswordResetCompleteView
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index),
    path('captcha/', include('captcha.urls')),
    path('userprofile/', include('userprofile.urls', namespace='userprofile')),
    # path('', include('userprofile.urls')),
    path('password_reset/', PasswordResetView.as_view(template_name='userprofile/password_reset_form.html',
                                                      email_template_name='userprofile/password_reset_email.html',),
         name='password_reset'),
    path('learn/', include('learn.urls')),  # 这里包含learn应用的URL配置
    path('SmartCenter/', include('SmartCenter.urls')),  
    path('DataCenter/', include('DataCenter.urls')),  
    path('BackManage/', include('BackManage.urls')),  
    path('MainInformation/', include('MainInformation.urls')),  
    path('UnderWater/', include('UnderWater.urls')),  

]
#设置静态文件路径
urlpatterns += staticfiles_urlpatterns()

5-团队作业/mytry/userprofile/urls.py
from django.urls import path
from .views import *

app_name = 'userprofile'

urlpatterns = [
    path('login/', user_login, name='login'),
    # path('', user_login),
    path('logout/', user_logout, name='logout'),
    path('register/', user_register, name='register'),
    path('profile/', user_profile, name='profile'),
]

5-团队作业/mytry/userprofile/models.py
from django.contrib.auth.models import AbstractUser, User
from django.db import models


class UserProfile(AbstractUser):
    avatar = models.ImageField(upload_to="avatar/%Y%m%d/", default="avatar/20210705/default.png", blank=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.username

5-团队作业/mytry/userprofile/forms.py
from django import forms

from userprofile.models import UserProfile


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField()


class RegisterForm(forms.ModelForm):
    password = forms.CharField()
    password2 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('username', 'email')

    def clean_password2(self):
        data = self.cleaned_data
        if data.get('password') == data.get('password2'):
            return data.get('password')
        else:
            return forms.ValidationError('两次输入的密码不一致，请重新输入！')


class ProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('avatar',)

5-团队作业/mytry/userprofile/views.py
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.shortcuts import render, redirect


from userprofile.forms import LoginForm, RegisterForm, ProfileForm
from userprofile.models import UserProfile as User
from django.contrib.auth import get_user_model

def user_login(request):
    if request.method == "GET":
        login_form = LoginForm()
        context = {"login_form": login_form}
        return render(request, "userprofile/login.html", context)
    else:
        login_form = LoginForm(data=request.POST)
        if login_form.is_valid():
            # data = login_form.cleaned_data
            # user = authenticate(username=data['username'], password=data['password'])
            data = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']
            user = authenticate(request, username=data, password=password)
            
             # 如果使用用户名没有找到用户，尝试邮箱登录
            if user is None:
                try:
                    user_by_email = User.objects.get(email=data)
                    # 使用邮箱找到用户后，再次尝试认证
                    user = authenticate(request, username=user_by_email.username, password=password)
                    authority = (User.objects.get(email=data).is_superuser & User.objects.get(email=data).is_staff)
                except User.DoesNotExist:
                    user_by_email = None
            else:
                authority = (User.objects.get(username=data).is_superuser & User.objects.get(username=data).is_staff)
            if user:
                login(request, user)
                # return redirect("article:article-list")
                # return redirect("index") 
                # return render(request, 'SmartCenter/trend.html', context)
                # return render(request, 'SmartCenter/your_template.html', {'context_data': data})
                # 数据查询，根据用户名查询出用户的权限
                # authority = (User.objects.get(username=data['username']).is_superuser & User.objects.get(username=data['username']).is_staff)

                if authority:
                    # return redirect("BackManage") 
                    return redirect("MainInformation") 
                    
                else:
                    # return redirect("MainInformation")
                    return redirect("MainInformation_user") 

            else:
                context = {'obj': login_form, 'error': '账号或密码错误，请重新输入！'}
                return render(request, 'userprofile/login.html', context)
        else:
            context = {'obj': login_form, 'error': login_form.errors}
            return render(request, 'userprofile/login.html', context)


def user_logout(request):
    logout(request)
    return redirect("article:article-list")


def user_register(request):
    if request.method == 'GET':
        register_form = RegisterForm()
        context = {'register_form': register_form}
        return render(request, 'userprofile/register.html', context)
    else:
        register_form = RegisterForm(data=request.POST)
        if register_form.is_valid():
            new_user = register_form.save(commit=False)
            new_user.set_password(register_form.cleaned_data['password'])
            new_user.save()
            return redirect("userprofile:login")
        else:
            context = {'obj': register_form, 'error': register_form.errors}
            return render(request, 'userprofile/register.html', context)


def user_profile(request):
    if request.method == "GET":
        articles = ArticlePost.objects.filter(author_id=request.user.id)
        context = {'articles': articles}
        return render(request, 'userprofile/profile.html', context)
    else:
        profile = UserProfile.objects.get(id=request.user.id)
        profile_form = ProfileForm(request.POST, request.FILES)
        if profile_form.is_valid():
            profile_form_data = profile_form.cleaned_data
            if 'avatar' in request.FILES:
                profile.avatar = profile_form_data['avatar']
            profile.save()
            return redirect('userprofile:profile')
        else:
            return HttpResponse('表单有误，请重新填写！')

5-团队作业/mytry/userprofile/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="zh-cn">
<head>
    <meta charset="UTF-8">
    <!-- 预留网页标题的位置 -->
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <!-- 引入代码高亮样式 -->
    <link rel="stylesheet" href="{% static 'md_css/monokai.css' %}">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <!-- 设置项目图标 -->
    <link rel="shortcut icon" href="{% static 'img/logo.png' %}" />
    <style>{% block style %}{% endblock %}</style>
</head>
<body>
    <!-- 引入导航栏 -->
    {% include 'header.html' %}
    <!-- 预留具体页面的位置 -->
    {% block content %}{% endblock content %}
    <!-- 引入注脚 -->
    {% include 'footer.html' %}
    <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="https://cdn.bootcss.com/jquery/3.3.1/jquery.min.js"></script>
</body>
</html>

5-团队作业/mytry/userprofile/templates/footer.html
<footer class="py-3 bg-dark fixed-bottom">
    <div class="container">
        <p class="m-0 text-center text-white">Copyright &copy; www.marvin.com 2021</p>
    </div>
</footer>

5-团队作业/mytry/userprofile/templates/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="#">
            Marvin's blog
        </a>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'article:article-list' %}">首页</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'article:article-create' %}">创作</a>
                </li>
            </ul>
        </div>
        <div class="collapse navbar-collapse justify-content-end">
            <ul class="navbar-nav">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle p-0" href="#" id="navbarDropdownMenuLink" role="button"
                           data-bs-toggle="dropdown" aria-expanded="false">
                            <img src="{{ user.avatar.url }}" class="rounded-circle" style="width: 40px;height: 40px;">
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <li><a class="dropdown-item" href="{% url 'userprofile:profile' %}"><i class="bi bi-person-fill"></i> 个人中心</a></li>
                            <li><a class="dropdown-item" href="{% url 'userprofile:logout' %}"><i class="bi bi-power"></i> 退出登录</a></li>
                        </ul>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'userprofile:login' %}">登录</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>